src/Plan_B/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ticket.urls')),
    path('', include('users.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('user/all', user_views.UsersView.as_view(), name='user-all'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

src/ticket/urls.py
from django.urls import path, include
from django_filters.views import FilterView
from . import views
from .filters import TicketFilter
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ticket/follow/', views.AddFollowerView.as_view(), name='follow'),
    # path('user/all', ),
    path('', views.TicketListView.as_view(), name='ticket-home'),
    path('ticket/search/', views.FilteredTicketList.as_view(), name='ticket-search'),
    path('ticket/<int:pk>/', views.TicketDetailView.as_view(), name='ticket-detail'),
    path('about/', views.about, name='ticket-about'),
    path('ticket/new/', views.TicketCreateView.as_view(), name='ticket-create'),
    path('ticket/<int:pk>/update/', views.TicketUpdateView.as_view(), name='ticket-update'),
    path('ticket/<int:pk>/delete/', views.TicketDeleteView.as_view(), name='ticket-delete'),
    # path('create/comment', views.CreateComment.as_view(), name='create-comment'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('profile/', views.profile, name='user-profile'),
    path('profile/<int:pk>', views.UserProfileView.as_view(), name='user-profileView')
]

src/ticket/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class PriorityChoice(models.TextChoices):
    Low = 'LW', _('Low')
    Normal = 'N', _('Normal')
    High = 'HI', _('High')


class StatusChoice(models.TextChoices):
    Open = 'OP', _('Open')
    In_Progress = 'IP', _('In Progress')
    Done = 'DN', _('Done')


class TypeChoice(models.TextChoices):
    Incident = "IN", _("Incident")
    Bug = "BG", _("Bug")


class ChoicePriorityDb(models.Model):
    title = models.CharField(max_length=100)
    charID = models.CharField(max_length=2)

    def __str__(self):  # __str__ for Python 3, __unicode__ for Python 2
        return self.title


class ChoiceStatusDb(models.Model):
    title = models.CharField(max_length=100)
    charID = models.CharField(max_length=2)

    def __str__(self):  # __str__ for Python 3, __unicode__ for Python 2
        return self.title


class ChoiceTypeDb(models.Model):
    title = models.CharField(max_length=100)
    charID = models.CharField(max_length=2)

    def __str__(self):  # __str__ for Python 3, __unicode__ for Python 2
        return self.title


class Ticket(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    date_expire = models.DateTimeField(blank=True, null=True)
    last_modified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=User)
    status = models.CharField(max_length=2, choices=StatusChoice.choices, default=StatusChoice.Open)
    type = models.CharField(max_length=2, choices=TypeChoice.choices, default=TypeChoice.Incident)
    priority = models.CharField(max_length=2, choices=PriorityChoice.choices, default=PriorityChoice.Normal)
    ticket_follower = models.ManyToManyField(User, related_name='ticket_follower', blank=True)
    assigned_user = models.ForeignKey(User, related_name='assigned_user', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('ticket-detail', kwargs={'pk': self.pk})


# Comment of a Ticket
class Comment(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, null=True, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('ticket-detail', kwargs={'pk': self.ticket.pk})

    class Meta:
        ordering = ['-date_posted']

src/ticket/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .widgets import BootstrapDateTimePickerInput
from .models import Ticket, Comment
from django.forms.widgets import SelectDateWidget


class TicketFilterForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['status', 'type']


class DateInput(forms.DateTimeInput):
    input_type = 'date'


class TicketCreateForm(forms.ModelForm):
    date_expire = forms.DateField(widget=DateInput, required=False)

    class Meta:
        model = Ticket
        fields = ['title', 'description', 'status', 'type', 'date_expire', 'status', 'priority', 'ticket_follower', 'assigned_user']
        # widgets = {'date_expire': SelectDateWidget}
        # exclude = ['date_expire', 'ticket_follower']


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

src/ticket/views.py
from django.forms import forms
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Ticket, Comment
from django.db.models import Q
from .filters import TicketFilter
from django_filters.views import FilterView
from .tables import TicketTable
from django_tables2 import SingleTableView, LazyPaginator
from .forms import TicketCreateForm, CommentCreateForm
from django.shortcuts import redirect


class AddFollowerView(LoginRequiredMixin, View):
    model = Ticket

    def post(self, request, *args, **kwargs):
        pk = request.POST.get('follow')
        ticket = Ticket.objects.get(pk=pk)

        if self.request.user in ticket.ticket_follower.all():
            ticket.ticket_follower.remove(self.request.user)
        else:
            ticket.ticket_follower.add(self.request.user)

        return redirect('/ticket/'+pk)


class TicketDetailView(LoginRequiredMixin, DetailView, CreateView):
    model = Ticket
    template_name = "ticket/comment.html"
    form_class = CommentCreateForm

    # def post(self, request, *args, **kwargs):
    #     print(request)
    #     print(args)
    #     print(kwargs)
    #

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.ticket = Ticket.objects.get(pk=self.kwargs.get('pk'))
        return super().form_valid(form)


class TicketListView(LoginRequiredMixin, ListView):
    model = Ticket
    template_name = 'ticket/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'tickets'
    ordering = ['-date_posted']

    def get_queryset(self):
        qs = super().get_queryset()

        tstatus = self.request.GET.get('status')
        ttype = self.request.GET.get('type')
        tprio = self.request.GET.get('priority')
        tfilter = self.request.GET.get('filter')
        # #filter
        if tstatus and tstatus != '*':
            qs = qs.filter(status__exact=tstatus)
        if ttype and ttype != '*':
            qs = qs.filter(type__exact=ttype)
        if tprio and tprio != '*':
            qs = qs.filter(priority__exact=tprio)
        if tfilter and tfilter != '':
            qs = qs.filter(Q(title__contains=tfilter) | Q(description__contains=tfilter))

        return qs


class FilteredTicketList(LoginRequiredMixin, FilterView, SingleTableView):
    model = Ticket
    template_name = 'ticket/ticket_search.html'
    filterset_class = TicketFilter
    table_class = TicketTable
    table_pagination = {"per_page": 10}


def about(request):
    return render(request, 'ticket/about.html', {'title': 'About'})


class TicketCreateView(LoginRequiredMixin, CreateView):
    model = Ticket
    form_class = TicketCreateForm
    # template_name = 'ticket/testgrid.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TicketUpdateView(LoginRequiredMixin, UpdateView):
    model = Ticket
    form_class = TicketCreateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        if form.instance.date_expire is None:
            form.instance.date_expire = Ticket.objects.get(pk=self.kwargs.get('pk')).date_expire
        return super().form_valid(form)


class TicketDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Ticket
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

src/ticket/templates/ticket/about.html
{% extends "ticket/base.html" %}
{% block content%}
   <article class="media content-section planb-window planb-text mt-3">
        <div class="media-body">
            <h1>Plan B Ticket System</h1>
            <p>Authoren: Dennis Stancu, Andreas Hofmann</p>
        </div>
   </article>
{% endblock content %}

src/ticket/templates/ticket/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% if title %}
        <title>Plan B - {{ title }}</title>
    {% else %}
        <title>Plan B</title>
    {% endif %}

    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{%  static 'ticket/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'ticket/sidebar.css' %}">
{#    <link rel="stylesheet" type="text/css" href="{%  static 'ticket/comment.css' %}">#}

    <!-- Bootstrap 4 -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


    <!--font-awesome-->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>



</head>

 <body>
  <div class="d-flex planb-bg" id="wrapper">
    <!-- Sidebar -->
    <div class="planb-bg border-right" id="sidebar-wrapper">
      <img width="230" src="{{ MEDIA_ROOT }}/media/Logo_planB.png"/>
      <div class="list-group list-group-flush">
        <a href="{% url 'ticket-home' %}" class="list-group-item list-group-item-action planb-bg planb-link"><i class="fa fa-align-justify"></i> Dashboard</a>
        {% if user.is_authenticated %}
            <a href="{% url 'ticket-create' %}" class="list-group-item list-group-item-action planb-bg planb-link"><i class="fa fa-plus-circle"></i> New Ticket</a>
            <a href="{% url 'ticket-search' %}" class="list-group-item list-group-item-action planb-bg planb-link"><i class="fa fa-filter"></i> Filter Page</a>
            <a href="{% url 'ticket-search' %}?assigned_user={{ user.pk }}" class="list-group-item list-group-item-action planb-bg planb-link"><i class="fa fa-list"></i> My Tickets</a>
            <a href="{% url 'ticket-search' %}?date_expire__lt={% now "m/d/Y" %}" class="list-group-item list-group-item-action planb-bg planb-link"><i class="fa fa-times-circle"></i> Expired Tickets</a>
            <a href="{% url 'user-profile'%}" class="list-group-item list-group-item-action planb-bg planb-link"><i class="fa fa-user-circle"></i> Profile</a>
            <a href="{% url 'user-all' %}" class="list-group-item list-group-item-action planb-bg planb-link"><i class="fa fa-users"></i> Users</a>
        {% endif %}
        <a href="{% url 'ticket-about' %}" class="list-group-item list-group-item-action planb-bg planb-link"><i class="fa fa-info-circle"></i> About</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-dark planb-bg border-bottom">
        <button class="btn bg-orange btn-outline-light planb-text mr-5" id="menu-toggle">Menu</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      {% if user.is_authenticated %}
          <form class="form-inline" action="{% url 'ticket-search' %}">
            <input class="form-control mr-sm-2 planb-bg planb-text" type="text" name="title__icontains" placeholder="Search Title">
            <button class="btn bg-orange btn-outline-light planb-text mr-5"  type="submit">Search</button>
          </form>
      {% endif %}

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link planb-link" href="{% url 'ticket-home' %}"><i class="fa fa-home" style="padding-right: 10px"></i>Home <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-item nav-link planb-link" href="{% url 'user-profile' %}"><i class="fa fa-user-circle" style="padding-right: 10px"></i>Profile</a></li>
                <li class="nav-item"><a class="nav-item nav-link planb-link" href="{% url 'logout' %}"><i class="fa fa-sign-out" style="padding-right: 10px"></i>Logout</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-item nav-link planb-link" href="{% url 'login' %}"><i class="fa fa-sign-in" style="padding-right: 10px"></i>Login</a></li>
                <li class="nav-item"><a class="nav-item nav-link planb-link" href="{% url 'register' %}"><i class="fa fa-registered" style="padding-right: 10px"></i>Register</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>


      <main role="main" class="container">
      <div class="row">
        <div class="col-md-12 mt-3">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            {% block sidebar %}{% endblock %}
        </div>
      </div>
    </main>

    </div>
    <!-- /page-content-wrapper -->

  </div>
  <!-- /wrapper -->

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

     <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
    </script>

  </body>
</html>

src/ticket/templates/ticket/comment.html
{% extends "ticket/ticket_detail.html" %}
{% load crispy_forms_tags %}
{% block comment %}

    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 text-orange"></legend>
                <div class="form-row">
                    <div class="small">
                    </div>
                    <div class="form-group col-md-12 mb-0">
                        {{ form.text|as_crispy_field}}
                    </div>
                </div>
            <input type="hidden" value="{{ object.id }}">
                <div class="form-row">
                    <button type="submit" class="btn bg-orange btn-outline-light planb-text mr-5", >Submit</button>
                </div>

        </fieldset>
    </form>
    <br>
    <h3 class="article-title text-orange">Comments</h3>
    {% for comment in object.comments.all %}
{#        <div class="chat-container">#}
{#            <img class="img" height="40" src="{{ comment.author.profile.image.url }}"/>#}
{#            <img class="rounded-circle account-img" src="{{ user.profile.image.url}}">#}
{#            <small class="text-muted">{{ comment.date_posted }}</small>#}
{#            <p class="clear-fix">{{ comment.text }}</p>#}
{#        </div>#}

        <hr>
        <li class="media">
                <a href="#" class="pull-left">
                    <img src="{{ comment.author.profile.image.url }}" height="50" width="50" class="rounded" style="padding-right: 5px">
                </a>
                <div class="media-body">
                    <span class="text-muted pull-right">
                        <small class="text-muted">{{ comment.date_posted }}</small>
                    </span>
                    <strong class="text">{{ comment.author }}</strong>
                    <p>
                        {{ comment.text }}
                    </p>
                </div>
        </li>
    {% endfor %}
{% endblock %}

src/ticket/templates/ticket/home.html
{% extends "ticket/base.html" %}
{% block content %}
    {% for ticket in tickets %}
       <article class="media content-section planb-window planb-text mt-3">
          <div class="media-body">
            <div >

              {% if ticket.priority == 'LW' %}
                <span class="badge badge-pill badge-success">
              {% elif ticket.priority == 'N' %}
                <span class="badge badge-pill badge-warning">
              {% else %}
                <span class="badge badge-pill badge-danger">
              {% endif %}
              {{ ticket.get_priority_display  }}</span>

            </div>
            <h2><a class="article-title planb-heading" href="{% url 'ticket-detail' ticket.id %}">{{ ticket.title }}</a></h2>
            <p class="article-content">{{ ticket.description|truncatechars:100 }}</p>
            <div class="article-metadata"></div>
              <a class="mr-2 planb-heading" href="#">{{ ticket.author }}</a>
              <small class="text-muted">{{ ticket.date_posted|date:"d.m.Y" }}</small>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

src/ticket/templates/ticket/sidebar.html
        <div class="content-section">
            <h3>Filterbar</h3>
              <ul class="list-group">

                <form action="{% url 'ticket-home' %}">
                    <div id="div_id_status" class="form-group">
                        <label for="id_status">Status</label>
                        <div class="">
                        <select name="status" class="select form-control" id="id_status">
                            <option value="*" selected>All</option>
                            <option value="OP">Open</option>
                            <option value="IP">In Progress</option>
                            <option value="DN">Done</option>
                        </select>
                        </div>
                    </div>
                    <div id="div_id_type" class="form-group">
                        <label for="id_type">Type</label>
                        <div class="">
                        <select name="type" class="select form-control" id="id_type">
                            <option value="*" selected>All</option>
                            <option value="IN">Incident</option>
                            <option value="BG">Bug</option>
                        </select>
                        </div>
                    </div>
                    <div id="div_id_priority" class="form-group">
                        <label for="id_priority">Priority </label>
                        <div class="">
                        <select name="priority" class="select form-control" id="id_priority">
                            <option value="*" selected>All</option>
                            <option value="LW">Low</option>
                            <option value="N">Normal</option>
                            <option value="HI">High</option>
                        </select>
                        </div>
                    </div>

                  <div class="form-group">
                    <label for="filter">Title / Description includes:</label>
                    <input name="filter" type="filter" class="form-control" placeholder="Search" id="filter">
                  </div>
                    <button class="btn btn-search" type="submit">Filter</button>
                </form>

              </ul>
          </div>

src/ticket/templates/ticket/ticket_confirm_delete.html
{% extends "ticket/base.html" %}
{% block content%}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the ticket "{{ object.title }}</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'ticket-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

src/ticket/templates/ticket/ticket_detail.html
{% extends "ticket/base.html" %}
{% load bootstrap4 %}
{% block content %}
   <article class="media content-section planb-window planb-text mt-3">
        <div class="media-body">
            <div class="article-metadata">
                <div class="row">
                    <div class="col-11">
                        <a class="mr-2 text-orange" href="#">{{ object.author }}</a>
                        <small class="text-muted">{{ object.date_posted|date:"d.m.Y" }}</small>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'ticket-update' object.id %}">Edit</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'ticket-delete' object.id %}">Delete</a>
                    </div>
                    <div class="col-1">
                        <form method="post" action="{% url 'follow'%}">
                            {% csrf_token %}
                                <input type="hidden" name="follow" value="{{ object.id }}">
                            {% if user in object.ticket_follower.all %}
                                <button class="btn btn-danger btn-sm mt-1 mb-1 align-items-end">-</button>
                            {% else %}
                                <button class="btn btn-success btn-sm mt-1 mb-1 align-items-end">+</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
{#        </div>#}
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="article-title text-orange">{{ object.title }}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4"><p class="article-content"><i class="fa fa-wrench" style="padding-right: 10px"></i>Status: {{ object.get_status_display }}</p></div>
                <div class="col-sm-4"><p class="article-content"><i class="fa fa-bolt" style="padding-right: 10px"></i>Type: {{ object.get_type_display }}</p></div>
                <div class="col-sm-4"><p class="article-content"><i class="fa fa-info-circle" style="padding-right: 10px"></i>Priority: {{ object.get_priority_display  }}</p></div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <p><i class="fa fa-user" style="padding-right: 10px"></i>Assigned User:
                        {% if object.assigned_user != null %}
{#                            {% if forloopcounter > 1 %}#}
                                {{ object.assigned_user  }}
{#                            {% endif %}#}
                        {% endif %}
                    </p>

                </div>

                <div class="col-sm-6">

                    <p><i class="fa fa-users" style="padding-right: 10px"></i>Follower:
                        {% for us in object.ticket_follower.all %}
                            {% if us != null %}
                                <a>{{ us }}</a>
                            {% endif %}
                        {% endfor %}
                    </p>
                </div>
            </div>

            <div class="row">

                <div class="col-sm-12">
                    {% if object.date_expire != null%}
                        <p class="article-content"><i class="fa fa-clock-o" style="padding-right: 10px"></i>Expire: <a id="demo"></a></p>
                    {% endif %}
                </div>

            </div>
            <div class="row">
                <div class="col-sm-12">
                <p class="article-content content-section planb-bg planb-text" >{{ object.description }}</p>
                </div>
            </div>
            <div class="row">
                <small class="text-muted">Date Posted: {{ object.date_posted|date:"d.m.Y H:i" }}, Last Modified: {{ object.last_modified|date:"d.m.Y H:i" }}</small>
            </div>
            {% block comment %}{% endblock %}
        </div>
      </div>
    </article>

    <script>
    var expire = "{{ object.date_expire.timestamp }}";
    // Set the date we're counting down to
    var countDownDate = expire*1000;
    // Update the count down every 1 second
    var x = setInterval(function() {
        // Get today's date and time
        var now = new Date().getTime();
        // Find the distance between now and the count down date
        var distance = countDownDate - now;
        // Time calculations for days, hours, minutes and seconds
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        // Display the result in the element with id="demo"
        document.getElementById("demo").innerHTML = days + "d " + hours + "h "
        + minutes + "m " + seconds + "s ";

        if (distance < 0) {
        clearInterval(x);
        document.getElementById("demo").innerHTML = "EXPIRED";
    }
    }, 1000);
    </script>
{% endblock content %}

src/ticket/templates/ticket/ticket_search.html
{% extends "ticket/base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load render_table from django_tables2 %}
{% block content%}

  <form method="get">
    <div class="content-section planb-window planb-text mt-3">
      <h4 class="planb-heading">Filter</h4>
      <div class="row">
        {% for field in filter.form %}
            <div class="form-group col-sm-4 col-md-3">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
        {% endfor %}
      </div>
      <button type="submit" class="btn bg-orange btn-outline-light planb-text">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
    </div>
  </form>

    {% render_table table %}

{% endblock content %}